### ISSUE TITLE
Tracking/Plan of op_driver

### ISSUE THREAD

**Issue by sabreshao** [carlushuang/miopen_cudnn_ops#1]
- [ ] Add support of enabling/disabling Tensor Core in convolution on NVIDIA/cuDNN backend.

- [ ] Add support of measure wall-time of both Find/Get interface on both NVIDIA/AMD backend.
    - [ ] Print out both kernel execution time and wall-time.
    - [ ] For NVIDIA/cuDNN backend, add both paths of cudnnFindConvolution[Direction]AlgorithmEx/cudnnGetConvolution[Direction]Algorithm. Direction can be Forward/BackwardData/BackwardFilter.

    - [ ] For AMD/MIOpen backend, add intermediate mode support, see below APIs for reference: miopenConvolutionForwardCompileSolution/miopenConvolutionForwardGetSolution/miopenConvolutionForwardImmediate

- [ ] Group/depthwise convolution support both in CPU/GPU side.

- [ ] Add support of tensor format on NVIDIA/cuDNN other than CUDNN_TENSOR_NCHW, such as CUDNN_TENSOR_NHWC and CUDNN_TENSOR_NCHW_VECT_C.
